import { Inter } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'flowbite/dist/flowbite.min.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Big Forum',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
